//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atfao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessEvents
    {
        public int ID { get; set; }
        public int EventType { get; set; }
        public string ObjectName { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int DirectionCode { get; set; }
        public string AccessPointPosition { get; set; }
        public string PassW26 { get; set; }
        public int AccessPointID { get; set; }
    }
}
